#!/usr/bin/env bash
# Script that installs Nginx server and configures redirection

# Install Nginx
apt-get -y update
apt-get -y install nginx

# Configure redirection
REDIRECT_CONFIG='
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    rewrite ^/redirect_me$ http://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;
}
'
sed -i "s|server {|&$REDIRECT_CONFIG|" /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
