#!/usr/bin/env bash
# Script that installs Nginx server
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
# Configure redirect for /redirect_me
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Anto236 permanent;/" /etc/nginx/sites-available/default
service nginx start
