#!/usr/bin/env bash
#script that displays a list of currently running processes
#Must show all processes, for all users
#including those which might not have a TTY
#Display in a user-oriented format
#Show process hierarchy

#ps  display currently running process
#aux display all processes
#shows the process hierarchy by indenting child processe
ps -aux --forest
