#!/usr/bin/env bash
#Starts manage_my_process

PIDFILE=/var/run/my_process.pid

start() {
    #start the manage_my_process script in background
    nohup ./manage_my_process >/dev/null 2>&1 &
    echo "$!" > "$PIDFILE"
}

stop() {
    #stop the manage_my_process script
    if [ -f "$PIDFILE" ]; then
        kill -15 "$(cat "$PIDFILE")" && rm -f "$PIDFILE"
    else
        echo "manage_my_process is not running"
    fi
}

case "$1" in 
    start)
       start
       echo "manage_my_process started"
       ;;
    stop)
       stop
       echo "manage_my_process stopped"
       ;;
    restart)
       stop
       start
       echo "manage_my_process restarted"
       ;;
    *)
       echo "Usage: manage_my_process {start|stop|restart}"
esac

exit 0
