#!/usr/bin/env bash
#script that displays To infinity and beyond indefinitely

#while true runs indefinately
while true;
do
	#echo will print the string
	echo "To infinity and beyond"

	#sleep 2  will pause the script for 2 seconds
	sleep 2
done
