#!/usr/bin/env bash
#Bash script that displays:
#To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal

#rap command, which will catch the SIGTERM
#signal and will display "I am invincible!!!"
trap 'echo "I am invincible!!!"' SIGTERM

#nfinite loop that will repeatedly display "To infinity and beyond"
#with a 2 second sleep in between each iteration.
while true;
do
	echo "To infinity and beyond"
	sleep 2
done
