#!/usr/bin/env bash
#script that displays numbers from 1 to 100
#Displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5
#Otherwise, displays the number
#In a list format

#loop through the range i to 100
for i in {1..100};
do
	#check if number is multiple of 3 and 5
	if [ $((i%3)) -eq 0 ] && [ $((i%5)) -eq 0 ];
	then
		echo "FizzBuzz"

	#check if number is multiple of 3
	elif [ $((i%3)) -eq 0 ];
	then
		echo "Fizz"

	#check if number is multiple of 5
	elif [ $((i%5)) -eq 0 ];
	then
		echo "Buzz"

	else
		echo "$i"
	fi
done
