#!/usr/bin/env bash
#script that displays Best School 10 times
#9th iteration, displays Best School
#then Hi on a new line

count=1
while [ $count -le 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	count=$((count+1))
done
