#!/usr/bin/env bash
#script that displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59
#You must use the while loop

hours=0
minutes=1
while [ $hours -le 12 ]
do
	echo "Hour: $hours"
	while [ $minutes -le 59 ]
	do
		echo "$minutes"
		minutes=$((minutes+1))
	done
	hours=$((hours+1))
	minutes=1
done
