#!/usr/bin/env bash
# Create a backup of the original /etc/hosts file
cp /etc/hosts ~/hosts.new

# Update the local host file to resolve localhost to 127.0.0.2
echo "127.0.0.2 localhost" > ~/hosts.new

# Update the local host file to resolve facebook.com to 8.8.8.8
echo "8.8.8.8 facebook.com" >> ~/hosts.new

# The cp command is used to copy the file ~/hosts.new to /etc/hosts
# The -f option forces the copy to overwrite the original file, even if it is read-only
cp -f ~/hosts.new /etc/hosts
